### PR TITLE
Changes to the user guide for 1.4 release

### PR DESCRIPTION
**Pull request by JackMiszencin**

### CODE REVIEW

**Comment by IanLawrence** [comment]
Looks all ok!
Does the title mean that we will skip a v1.3 release of this guide? Current tags are v1.1 and v1.2

**Comment by JackMiszencin** [comment]
Yeah, v1.3 is pretty much the same as v1.2 so far as the docs go.

**Comment by IanLawrence** [comment]
OK, can you tag as v1.4 when everything is ready?

**Comment by pnabutovsky** [comment]
@IanLawrence @JackMiszencin  I would hold off tagging with v1.4 until we have some dev stability. The v1.4 development is still on-going, and some UAT preference changes may alter the look/feel of things.

**Pull request merged**
