### PR TITLE
Maint 1.2

### PR DESCRIPTION
**Pull request by JackMiszencin**
All changes made by Megs and Tessa for 1.2, removed MRM references.

### CODE REVIEW

**Comment by IanLawrence** [comment]
Hi
Where you have removed some MRM references (like in commit d5dc3cc5b1f215fb4b0c3b260fc7dcc28c06f154) it seems to have messed up a little the formatting (at least it does when i run the book locally using gitbook serve) Check out the differences 
**New**
unformatted
**Old**
formatted

**Comment by JackMiszencin** [comment]
@IanLawrence , made some changes to try and fix that spacing problem. Let me know if you think it looks good, or if I need to make some more fixes.

**Comment by IanLawrence** [comment]
Looks better now, thanks!. You ok with this @pnabutovsky ? Shall we merge and tag as v1.2?

**Review by pnabutovsky — APPROVED** [review]
Looking good! @IanLawrence will you do the primary documentation merge honors for now?

**Comment by pnabutovsky** [comment]
Let's keep the maint_1.2 branch around (along with a future maint_1.3 branch that we should create once all this is merges and right before Jack moves on to v1.4 docs).

**Comment by IanLawrence** [comment]
Merged. Thanks @JackMiszencin !

**Pull request closed without merging**
